# Generated by Django 3.2.1 on 2021-08-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Person_id', models.CharField(max_length=50, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Person_id', models.CharField(max_length=50, null=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('sex', models.CharField(max_length=10, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FPPI.father')),
                ('Mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FPPI.mother')),
            ],
        ),
        migrations.CreateModel(
            name='Souse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Person', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='FPPI.person')),
            ],
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Person', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='FPPI.person')),
            ],
        ),
        migrations.CreateModel(
            name='Sister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Person', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='FPPI.person')),
            ],
        ),
        migrations.CreateModel(
            name='Dather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Person', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='FPPI.person')),
            ],
        ),
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=1)),
                ('Family', models.CharField(max_length=100, null=1)),
                ('CodeNational', models.CharField(max_length=100, null=1)),
                ('Birth', models.DateField(null=1)),
                ('Person', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='FPPI.person')),
            ],
        ),
    ]
