# Generated by Django 3.2.1 on 2021-08-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0004_auto_20210827_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
