# Generated by Django 3.2.1 on 2021-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0006_remove_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='MoreInfo',
            field=models.TextField(max_length=3000, null=1),
            preserve_default=1,
        ),
    ]
