# Generated by Django 3.2.1 on 2021-09-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0008_alter_person_moreinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Address',
            field=models.CharField(max_length=200, null=1),
            preserve_default=1,
        ),
    ]
