# Generated by Django 3.2.1 on 2021-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0010_remove_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Adr',
            field=models.CharField(max_length=200, null=1),
            preserve_default=1,
        ),
    ]
