# Generated by Django 3.1.5 on 2021-09-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0014_auto_20210913_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Brother',
            field=models.ManyToManyField(to='FPPI.Brother'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Sister',
            field=models.ManyToManyField(to='FPPI.Sister'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Souse',
            field=models.ManyToManyField(to='FPPI.Souse'),
        ),
    ]
