# Generated by Django 3.1.5 on 2021-12-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0016_person_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.ImageField(null=1, upload_to='Profile/'),
        ),
    ]
