# Generated by Django 3.1.5 on 2021-12-26 13:52

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0017_auto_20211226_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.ImageField(null=1, storage=django.core.files.storage.FileSystemStorage(location='/media/Profile'), upload_to=''),
        ),
    ]
