# Generated by Django 3.1.5 on 2021-12-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPPI', '0018_auto_20211226_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='upload',
            field=models.ImageField(null=1, upload_to='Profile/'),
        ),
    ]
